env:
  es6: true
  browser: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:promise/recommended
  - plugin:prettier/recommended
eslintConfig:
  rules:
    no-unused-vars: error
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  react/prop-types: 0
